version: "3.6"

services:
  client-service:
    image: client-service:dev
    user: "1000:1000"
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    env_file:
      - ./development.env
    ports:
      - 3002:3002
    volumes:
      - node_modules_cache:/usr/app/node_modules
      - ./package.json:/usr/app/package.json
      - ./yarn.lock:/usr/app/yarn.lock
      - ./.eslintrc.json:/usr/app/.eslintrc.json
      - ./.eslintignore:/usr/app/.eslintignore
      - ./src:/usr/app/src

volumes:
  node_modules_cache: {}